export const GET_POPULAR_MOVIES = "GET_POPULAR_MOVIES";
export const GET_POPULAR_MOVIES_SUCCESS = "GET_POPULAR_MOVIES_SUCCESS";
export const GET_POPULAR_MOVIES_FAIL = "GET_POPULAR_MOVIES_FAIL";

export const GET_TOP_RATED_MOVIES = "GET_TOP_RATED_MOVIES";
export const GET_TOP_RATED_MOVIES_SUCCESS = "GET_TOP_RATED_MOVIES_SUCCESS";
export const GET_TOP_RATED_MOVIES_FAIL = "GET_TOP_RATED_MOVIES_FAIL";

export const GET_UPCOMING_MOVIES = "GET_UPCOMING_MOVIES";
export const GET_UPCOMING_MOVIES_SUCCESS = "GET_UPCOMING_MOVIES_SUCCESS";
export const GET_UPCOMING_MOVIES_FAIL = "GET_UPCOMING_MOVIES_FAIL";

export const GET_SEARCH_MOVIES = "GET_SEARCH_MOVIES";
export const GET_SEARCH_MOVIES_SUCCESS = "GET_SEARCH_MOVIES_SUCCESS";
export const GET_SEARCH_MOVIES_FAIL = "GET_SEARCH_MOVIES_FAIL";

export const CLEAN_SEARCH_MOVIES = "CLEAN_SEARCH_MOVIES";

export const GET_MOVIE_CATEGORIES = "GET_MOVIE_CATEGORIES";
export const GET_MOVIE_CATEGORIES_SUCCESS = "GET_MOVIE_CATEGORIES_SUCCESS";
export const GET_MOVIE_CATEGORIES_FAIL = "GET_MOVIE_CATEGORIES_FAIL";

export const GET_SELECTED_MOVIE_CATEGORY = "GET_SELECTED_MOVIE_CATEGORY";
export const GET_SELECTED_MOVIE_CATEGORY_SUCCESS =
  "GET_SELECTED_MOVIE_CATEGORY_SUCCESS";
export const GET_SELECTED_MOVIE_CATEGORY_FAIL =
  "GET_SELECTED_MOVIE_CATEGORY_FAIL";

export const GET_MOVIE_DETAIL_TRAILER = "GET_MOVIE_DETAIL_TRAILER";
export const GET_MOVIE_DETAIL_TRAILER_SUCCESS =
  "GET_MOVIE_DETAIL_TRAILER_SUCCESS";
export const GET_MOVIE_DETAIL_TRAILER_FAIL = "GET_MOVIE_DETAIL_TRAILER_FAIL";

export const GET_MOVIE_DETAIL_CAST = "GET_MOVIE_DETAIL_CAST";
export const GET_MOVIE_DETAIL_CAST_SUCCESS = "GET_MOVIE_DETAIL_CAST_SUCCESS";
export const GET_MOVIE_DETAIL_CAST_FAIL = "GET_MOVIE_DETAIL_CAST_FAIL";

//---------------------------------------------------------------------------

export const GET_POPULAR_TV_SERIES = "GET_POPULAR_TV_SERIES";
export const GET_POPULAR_TV_SERIES_SUCCESS = "GET_POPULAR_TV_SERIES_SUCCESS";
export const GET_POPULAR_TV_SERIES_FAIL = "GET_POPULAR_TV_SERIES_FAIL";

export const GET_TOP_RATED_TV_SERIES = "GET_TOP_RATED_MOVIES";
export const GET_TOP_RATED_TV_SERIES_SUCCESS =
  "GET_TOP_RATED_TV_SERIES_SUCCESS";
export const GET_TOP_RATED_TV_SERIES_FAIL = "GET_TOP_RATED_MOVIES_FAIL";

export const GET_ON_THE_AIR_TV_SERIES = "GET_ON_THE_AIR_TV_SERIES";
export const GET_ON_THE_AIR_TV_SERIES_SUCCESS =
  "GET_ON_THE_AIR_TV_SERIES_SUCCESS";
export const GET_ON_THE_AIR_TV_SERIES_FAIL = "GET_ON_THE_AIR_TV_SERIES_FAIL";

export const GET_SEARCH_TV_SERIES = "GET_SEARCH_TV_SERIES";
export const GET_SEARCH_TV_SERIES_SUCCESS = "GET_SEARCH_TV_SERIES_SUCCESS";
export const GET_SEARCH_TV_SERIES_FAIL = "GET_SEARCH_TV_SERIES_FAIL";

export const CLEAN_SEARCH_TV_SERIES = "CLEAN_SEARCH_TV_SERIES";

export const GET_TV_SERIES_CATEGORIES = "GET_TV_SERIES_CATEGORIES";
export const GET_TV_SERIES_CATEGORIES_SUCCESS =
  "GET_TV_SERIES_CATEGORIES_SUCCESS";
export const GET_TV_SERIES_CATEGORIES_FAIL = "GET_TV_SERIES_CATEGORIES_FAIL";

export const GET_SELECTED_TV_SERIES_CATEGORY =
  "GET_SELECTED_TV_SERIES_CATEGORY";
export const GET_SELECTED_TV_SERIES_CATEGORY_SUCCESS =
  "GET_SELECTED_TV_SERIES_CATEGORY_SUCCESS";
export const GET_SELECTED_TV_SERIES_CATEGORY_FAIL =
  "GET_SELECTED_TV_SERIES_CATEGORY_FAIL";

export const GET_TV_SERIE_DETAIL_TRAILER = "GET_TV_SERIE_DETAIL_TRAILER";
export const GET_TV_SERIE_DETAIL_TRAILER_SUCCESS =
  "GET_TV_SERIE_DETAIL_TRAILER_SUCCESS";
export const GET_TV_SERIES_DETAIL_TRAILER_FAIL =
  "GET_TV_SERIE_DETAIL_TRAILER_FAIL";

export const GET_TV_SERIE_DETAIL_CAST = "GET_TV_SERIE_DETAIL_CAST";
export const GET_TV_SERIE_DETAIL_CAST_SUCCESS =
  "GET_TV_SERIE_DETAIL_CAST_SUCCESS";
export const GET_TV_SERIE_DETAIL_CAST_FAIL = "GET_TV_SERIE_DETAIL_CAST_FAIL";

//-----------------------------------------------------------------------------
